// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated from 101 original Animal Island UI SVG icons.

/// Enumeration of all 101 Animal Island UI cute icons.
enum AnimalIconName {
  airplane,
  anchor,
  apple,
  balloon,
  bear,
  bee,
  bell,
  bicycle,
  bird,
  book,
  bookmark,
  bulb,
  butterfly,
  cactus,
  cake,
  calendar,
  camera,
  candle,
  car,
  cart,
  cat,
  chat,
  check,
  cherry,
  clock,
  close,
  cloud,
  code,
  coffee,
  compass,
  creditCard,
  dog,
  donut,
  download,
  edit,
  eye,
  file,
  fish,
  flag,
  flame,
  flower,
  folder,
  fox,
  frog,
  gift,
  globe,
  headphones,
  heart,
  home,
  icecream,
  image,
  key,
  ladybug,
  lamp,
  leaf,
  lemon,
  location,
  lock,
  magnet,
  mail,
  map,
  mic,
  moon,
  mushroom,
  music,
  owl,
  paintbrush,
  pencil,
  penguin,
  phone,
  play,
  plus,
  rabbit,
  rainbow,
  refresh,
  rocket,
  sailboat,
  save,
  search,
  settings,
  share,
  shoppingBag,
  smile,
  snail,
  snowflake,
  star,
  strawberry,
  sun,
  tag,
  thermometer,
  thumbsUp,
  train,
  trash,
  tree,
  trophy,
  umbrella,
  upload,
  user,
  video,
  watermelon,
  wifi,
}

/// Metadata entry for icon catalog exploration.
class AnimalIconItem {
  final AnimalIconName name;
  final String label;
  final String pascalName;

  const AnimalIconItem({
    required this.name,
    required this.label,
    required this.pascalName,
  });
}

/// Complete catalog of all 101 Animal Island icons.
const List<AnimalIconItem> animalIconList = [
  AnimalIconItem(name: AnimalIconName.airplane, label: 'Airplane', pascalName: 'AirplaneIcon'),
  AnimalIconItem(name: AnimalIconName.anchor, label: 'Anchor', pascalName: 'AnchorIcon'),
  AnimalIconItem(name: AnimalIconName.apple, label: 'Apple', pascalName: 'AppleIcon'),
  AnimalIconItem(name: AnimalIconName.balloon, label: 'Balloon', pascalName: 'BalloonIcon'),
  AnimalIconItem(name: AnimalIconName.bear, label: 'Bear', pascalName: 'BearIcon'),
  AnimalIconItem(name: AnimalIconName.bee, label: 'Bee', pascalName: 'BeeIcon'),
  AnimalIconItem(name: AnimalIconName.bell, label: 'Bell', pascalName: 'BellIcon'),
  AnimalIconItem(name: AnimalIconName.bicycle, label: 'Bicycle', pascalName: 'BicycleIcon'),
  AnimalIconItem(name: AnimalIconName.bird, label: 'Bird', pascalName: 'BirdIcon'),
  AnimalIconItem(name: AnimalIconName.book, label: 'Book', pascalName: 'BookIcon'),
  AnimalIconItem(name: AnimalIconName.bookmark, label: 'Bookmark', pascalName: 'BookmarkIcon'),
  AnimalIconItem(name: AnimalIconName.bulb, label: 'Bulb', pascalName: 'BulbIcon'),
  AnimalIconItem(name: AnimalIconName.butterfly, label: 'Butterfly', pascalName: 'ButterflyIcon'),
  AnimalIconItem(name: AnimalIconName.cactus, label: 'Cactus', pascalName: 'CactusIcon'),
  AnimalIconItem(name: AnimalIconName.cake, label: 'Cake', pascalName: 'CakeIcon'),
  AnimalIconItem(name: AnimalIconName.calendar, label: 'Calendar', pascalName: 'CalendarIcon'),
  AnimalIconItem(name: AnimalIconName.camera, label: 'Camera', pascalName: 'CameraIcon'),
  AnimalIconItem(name: AnimalIconName.candle, label: 'Candle', pascalName: 'CandleIcon'),
  AnimalIconItem(name: AnimalIconName.car, label: 'Car', pascalName: 'CarIcon'),
  AnimalIconItem(name: AnimalIconName.cart, label: 'Cart', pascalName: 'CartIcon'),
  AnimalIconItem(name: AnimalIconName.cat, label: 'Cat', pascalName: 'CatIcon'),
  AnimalIconItem(name: AnimalIconName.chat, label: 'Chat', pascalName: 'ChatIcon'),
  AnimalIconItem(name: AnimalIconName.check, label: 'Check', pascalName: 'CheckIcon'),
  AnimalIconItem(name: AnimalIconName.cherry, label: 'Cherry', pascalName: 'CherryIcon'),
  AnimalIconItem(name: AnimalIconName.clock, label: 'Clock', pascalName: 'ClockIcon'),
  AnimalIconItem(name: AnimalIconName.close, label: 'Close', pascalName: 'CloseIcon'),
  AnimalIconItem(name: AnimalIconName.cloud, label: 'Cloud', pascalName: 'CloudIcon'),
  AnimalIconItem(name: AnimalIconName.code, label: 'Code', pascalName: 'CodeIcon'),
  AnimalIconItem(name: AnimalIconName.coffee, label: 'Coffee', pascalName: 'CoffeeIcon'),
  AnimalIconItem(name: AnimalIconName.compass, label: 'Compass', pascalName: 'CompassIcon'),
  AnimalIconItem(name: AnimalIconName.creditCard, label: 'CreditCard', pascalName: 'CreditCardIcon'),
  AnimalIconItem(name: AnimalIconName.dog, label: 'Dog', pascalName: 'DogIcon'),
  AnimalIconItem(name: AnimalIconName.donut, label: 'Donut', pascalName: 'DonutIcon'),
  AnimalIconItem(name: AnimalIconName.download, label: 'Download', pascalName: 'DownloadIcon'),
  AnimalIconItem(name: AnimalIconName.edit, label: 'Edit', pascalName: 'EditIcon'),
  AnimalIconItem(name: AnimalIconName.eye, label: 'Eye', pascalName: 'EyeIcon'),
  AnimalIconItem(name: AnimalIconName.file, label: 'File', pascalName: 'FileIcon'),
  AnimalIconItem(name: AnimalIconName.fish, label: 'Fish', pascalName: 'FishIcon'),
  AnimalIconItem(name: AnimalIconName.flag, label: 'Flag', pascalName: 'FlagIcon'),
  AnimalIconItem(name: AnimalIconName.flame, label: 'Flame', pascalName: 'FlameIcon'),
  AnimalIconItem(name: AnimalIconName.flower, label: 'Flower', pascalName: 'FlowerIcon'),
  AnimalIconItem(name: AnimalIconName.folder, label: 'Folder', pascalName: 'FolderIcon'),
  AnimalIconItem(name: AnimalIconName.fox, label: 'Fox', pascalName: 'FoxIcon'),
  AnimalIconItem(name: AnimalIconName.frog, label: 'Frog', pascalName: 'FrogIcon'),
  AnimalIconItem(name: AnimalIconName.gift, label: 'Gift', pascalName: 'GiftIcon'),
  AnimalIconItem(name: AnimalIconName.globe, label: 'Globe', pascalName: 'GlobeIcon'),
  AnimalIconItem(name: AnimalIconName.headphones, label: 'Headphones', pascalName: 'HeadphonesIcon'),
  AnimalIconItem(name: AnimalIconName.heart, label: 'Heart', pascalName: 'HeartIcon'),
  AnimalIconItem(name: AnimalIconName.home, label: 'Home', pascalName: 'HomeIcon'),
  AnimalIconItem(name: AnimalIconName.icecream, label: 'Icecream', pascalName: 'IcecreamIcon'),
  AnimalIconItem(name: AnimalIconName.image, label: 'Image', pascalName: 'AnimalImageIcon'),
  AnimalIconItem(name: AnimalIconName.key, label: 'Key', pascalName: 'KeyIcon'),
  AnimalIconItem(name: AnimalIconName.ladybug, label: 'Ladybug', pascalName: 'LadybugIcon'),
  AnimalIconItem(name: AnimalIconName.lamp, label: 'Lamp', pascalName: 'LampIcon'),
  AnimalIconItem(name: AnimalIconName.leaf, label: 'Leaf', pascalName: 'LeafIcon'),
  AnimalIconItem(name: AnimalIconName.lemon, label: 'Lemon', pascalName: 'LemonIcon'),
  AnimalIconItem(name: AnimalIconName.location, label: 'Location', pascalName: 'LocationIcon'),
  AnimalIconItem(name: AnimalIconName.lock, label: 'Lock', pascalName: 'LockIcon'),
  AnimalIconItem(name: AnimalIconName.magnet, label: 'Magnet', pascalName: 'MagnetIcon'),
  AnimalIconItem(name: AnimalIconName.mail, label: 'Mail', pascalName: 'MailIcon'),
  AnimalIconItem(name: AnimalIconName.map, label: 'Map', pascalName: 'MapIcon'),
  AnimalIconItem(name: AnimalIconName.mic, label: 'Mic', pascalName: 'MicIcon'),
  AnimalIconItem(name: AnimalIconName.moon, label: 'Moon', pascalName: 'MoonIcon'),
  AnimalIconItem(name: AnimalIconName.mushroom, label: 'Mushroom', pascalName: 'MushroomIcon'),
  AnimalIconItem(name: AnimalIconName.music, label: 'Music', pascalName: 'MusicIcon'),
  AnimalIconItem(name: AnimalIconName.owl, label: 'Owl', pascalName: 'OwlIcon'),
  AnimalIconItem(name: AnimalIconName.paintbrush, label: 'Paintbrush', pascalName: 'PaintbrushIcon'),
  AnimalIconItem(name: AnimalIconName.pencil, label: 'Pencil', pascalName: 'PencilIcon'),
  AnimalIconItem(name: AnimalIconName.penguin, label: 'Penguin', pascalName: 'PenguinIcon'),
  AnimalIconItem(name: AnimalIconName.phone, label: 'Phone', pascalName: 'PhoneIcon'),
  AnimalIconItem(name: AnimalIconName.play, label: 'Play', pascalName: 'PlayIcon'),
  AnimalIconItem(name: AnimalIconName.plus, label: 'Plus', pascalName: 'PlusIcon'),
  AnimalIconItem(name: AnimalIconName.rabbit, label: 'Rabbit', pascalName: 'RabbitIcon'),
  AnimalIconItem(name: AnimalIconName.rainbow, label: 'Rainbow', pascalName: 'RainbowIcon'),
  AnimalIconItem(name: AnimalIconName.refresh, label: 'Refresh', pascalName: 'RefreshIcon'),
  AnimalIconItem(name: AnimalIconName.rocket, label: 'Rocket', pascalName: 'RocketIcon'),
  AnimalIconItem(name: AnimalIconName.sailboat, label: 'Sailboat', pascalName: 'SailboatIcon'),
  AnimalIconItem(name: AnimalIconName.save, label: 'Save', pascalName: 'SaveIcon'),
  AnimalIconItem(name: AnimalIconName.search, label: 'Search', pascalName: 'SearchIcon'),
  AnimalIconItem(name: AnimalIconName.settings, label: 'Settings', pascalName: 'SettingsIcon'),
  AnimalIconItem(name: AnimalIconName.share, label: 'Share', pascalName: 'ShareIcon'),
  AnimalIconItem(name: AnimalIconName.shoppingBag, label: 'ShoppingBag', pascalName: 'ShoppingBagIcon'),
  AnimalIconItem(name: AnimalIconName.smile, label: 'Smile', pascalName: 'SmileIcon'),
  AnimalIconItem(name: AnimalIconName.snail, label: 'Snail', pascalName: 'SnailIcon'),
  AnimalIconItem(name: AnimalIconName.snowflake, label: 'Snowflake', pascalName: 'SnowflakeIcon'),
  AnimalIconItem(name: AnimalIconName.star, label: 'Star', pascalName: 'StarIcon'),
  AnimalIconItem(name: AnimalIconName.strawberry, label: 'Strawberry', pascalName: 'StrawberryIcon'),
  AnimalIconItem(name: AnimalIconName.sun, label: 'Sun', pascalName: 'SunIcon'),
  AnimalIconItem(name: AnimalIconName.tag, label: 'Tag', pascalName: 'TagIcon'),
  AnimalIconItem(name: AnimalIconName.thermometer, label: 'Thermometer', pascalName: 'ThermometerIcon'),
  AnimalIconItem(name: AnimalIconName.thumbsUp, label: 'ThumbsUp', pascalName: 'ThumbsUpIcon'),
  AnimalIconItem(name: AnimalIconName.train, label: 'Train', pascalName: 'TrainIcon'),
  AnimalIconItem(name: AnimalIconName.trash, label: 'Trash', pascalName: 'TrashIcon'),
  AnimalIconItem(name: AnimalIconName.tree, label: 'Tree', pascalName: 'TreeIcon'),
  AnimalIconItem(name: AnimalIconName.trophy, label: 'Trophy', pascalName: 'TrophyIcon'),
  AnimalIconItem(name: AnimalIconName.umbrella, label: 'Umbrella', pascalName: 'UmbrellaIcon'),
  AnimalIconItem(name: AnimalIconName.upload, label: 'Upload', pascalName: 'UploadIcon'),
  AnimalIconItem(name: AnimalIconName.user, label: 'User', pascalName: 'UserIcon'),
  AnimalIconItem(name: AnimalIconName.video, label: 'Video', pascalName: 'VideoIcon'),
  AnimalIconItem(name: AnimalIconName.watermelon, label: 'Watermelon', pascalName: 'WatermelonIcon'),
  AnimalIconItem(name: AnimalIconName.wifi, label: 'Wifi', pascalName: 'WifiIcon'),
];
